// Code generated by mockery v2.43.1. DO NOT EDIT.

package mocks

import (
	domains "technical-test-be-abc/domains"

	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// CreateTodo provides a mock function with given fields: _a0
func (_m *Repository) CreateTodo(_a0 domains.Todo) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for CreateTodo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(domains.Todo) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteTodo provides a mock function with given fields: id, userId
func (_m *Repository) DeleteTodo(id string, userId string) error {
	ret := _m.Called(id, userId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTodo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(id, userId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllTodo provides a mock function with given fields: userId
func (_m *Repository) GetAllTodo(userId string) ([]domains.Todo, error) {
	ret := _m.Called(userId)

	if len(ret) == 0 {
		panic("no return value specified for GetAllTodo")
	}

	var r0 []domains.Todo
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]domains.Todo, error)); ok {
		return rf(userId)
	}
	if rf, ok := ret.Get(0).(func(string) []domains.Todo); ok {
		r0 = rf(userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domains.Todo)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTodoById provides a mock function with given fields: id
func (_m *Repository) GetTodoById(id string) (domains.Todo, error) {
	ret := _m.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetTodoById")
	}

	var r0 domains.Todo
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (domains.Todo, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) domains.Todo); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(domains.Todo)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateStatusTodo provides a mock function with given fields: id, status, userId
func (_m *Repository) UpdateStatusTodo(id string, status bool, userId string) error {
	ret := _m.Called(id, status, userId)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStatusTodo")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, bool, string) error); ok {
		r0 = rf(id, status, userId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateTodoById provides a mock function with given fields: id, userId, _a2
func (_m *Repository) UpdateTodoById(id string, userId string, _a2 domains.Todo) error {
	ret := _m.Called(id, userId, _a2)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTodoById")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, domains.Todo) error); ok {
		r0 = rf(id, userId, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
